backend:
  name: git-gateway
  branch: main

media_folder: "Resources"
public_folder: "/Resources"

collections:
  - name: "portfolio"
    label: "Portfolio Items"
    folder: "Resources/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "services"
    label: "Services"
    folder: "Resources/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Service Name", name: "title", widget: "string" }
      - { label: "Details", name: "description", widget: "text" }
